# Generated by Django 6.0 on 2026-01-07 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_update_userprofile_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='admin_id',
            field=models.ForeignKey(blank=True, help_text="Required if role is 'user'. Must reference an admin user. NULL if role is 'admin'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
