# Generated by Django 6.0 on 2026-01-05 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='session',
            new_name='session_ses_user_id_108f96_idx',
            old_name='session_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='session',
            new_name='session_ses_status_18cbaa_idx',
            old_name='session_status_idx',
        ),
    ]
