# Generated by Django 6.0 on 2026-01-05 04:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('session', '0002_rename_session_user_created_idx_session_ses_user_id_108f96_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('command', models.TextField()),
                ('command_type', models.CharField(choices=[('shell', 'Shell'), ('file_read', 'File Read'), ('file_write', 'File Write'), ('file_edit', 'File Edit'), ('other', 'Other')], max_length=20)),
                ('output', models.TextField(blank=True)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('execution_time_ms', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('error', 'Error')], max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='command_executions', to='session.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_executions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'command_executions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='command_exe_user_id_6867d1_idx'), models.Index(fields=['command_type'], name='command_exe_command_9178b7_idx'), models.Index(fields=['status'], name='command_exe_status_6dd4e3_idx'), models.Index(fields=['session'], name='command_exe_session_d631ad_idx')],
            },
        ),
    ]
